name: Sheenam Build Pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
    - name: Setting Up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300
        include-prerelease: false
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
